apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app.kubernetes.io/name: app-b
    app.kubernetes.io/instance: release-name
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app-b
    app.kubernetes.io/instance: release-name
