apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-b
  namespace: default
spec:
  encryptedData:
    APPB_FOOPASSWORD: AgBP5OA5XpXdTAKIZj+aKWx9YWZ5GU99+b5M1SL5AeJIwt4UTFuKzZCFFMlXAWFKgDzAvunhkAW5JVkufi4RzYribW+IDPrfdNSl7hH+0yvHOEQn05gcKqMxtPStzclWMWy2DAiCEHTmELM0ydkW7J3uwVT/sUCps9P9MN/nGcYgHH1medz/Ly8xmhvN/x4H0hQlO7Awrs1JlI1rUw0L8mSZXW5UKLZiYs7UgK1AHSlhgiea4kxcbWkOOjEW8qUeZQbkAXq71JABK5WwoEQN+F8JKdfxZaK+w688hP9mTX4qmkqlwYQvC2X6y3aBZuROXq8egn4r9XaKiFrUoKCfLobZtrUmf5S/mc/xQKpIYRD9252N88iXN6Mne8FkWNWzyArHi3ETx4PYJlTwT5BM7CSjVhBD0u+f8h+RbMUhZd2w3sw+Efr1Npy8YqS0PjN6X8QxxTST8yS7HeQk6HXcJY0Q1xFXaQm5hjfZl7FXEIjwL6Wm0AnkxD8pG9xjLPLDxZihpbc+NqgU/enqbRtGHySuHKSgQd1tdIDhn4sqygLmy2JJ8QqQhj/hOYaKlRaujTz78RXIn7TfRm0/PPW9l404LaG9qC+6B2mPgXuVXjYJtZhCvmlRgbxF5Qc1N+eIdq+HIdGvuixFHBT5itOPw62Uu0KEwr+W2JcExU0aVvDCFWyqReVgoyFz7/5RbYQ113RKJjjvjPRABFrSVUZlA5x6rBHRpw==
